CREATE TABLE "mockInterview" (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    jsonMockResp varchar NOT NULL,
    jobPosition varchar NOT NULL,
    jobDesc varchar NOT NULL,
    jobExperience varchar NOT NULL,
    category varchar(100),
    createdBy varchar NOT NULL,
    createdAt varchar,
    mockId varchar NOT NULL
);

CREATE TABLE "userAnswer" (
	"id" serial PRIMARY KEY NOT NULL,
	"mockId" varchar NOT NULL,
	"question" varchar NOT NULL,
	"correctAns" text,
	"userAns" text,
	"feedback" text,
	"rating" varchar,
	"suggestions" text,
	"userEmail" varchar,
	"createdAt" varchar,
	"isFollowUp" boolean DEFAULT false,
	"needsFollowUp" boolean DEFAULT false
);
