CREATE TABLE "JobPost" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
	"jobTitle" varchar(255),
	"jobCategories" varchar(255)[],
	"jobTypes" varchar(255)[],
	"workplace" varchar(100),
	"country" varchar(100),
	"city" varchar(100),
	"careerLevel" varchar(100),
	"minExperience" integer,
	"maxExperience" integer,
	"minSalary" integer,
	"maxSalary" integer,
	"currency" varchar(20),
	"period" varchar(20),
	"hideSalary" boolean,
	"additionalSalary" varchar(255),
	"vacancies" integer,
	"jobDescription" text,
	"jobRequirements" text,
	"skills" varchar(255),
	"gender" varchar(50),
	"education" varchar(100),
	"academicExcellence" boolean,
	"recruiterEmail" varchar(255),
	"recruiterName" varchar(255),
	"createdAt" timestamp DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "mockInterview" ADD COLUMN "jobPostId" integer;--> statement-breakpoint
ALTER TABLE "CallInterview" ADD COLUMN "jobPostId" integer;--> statement-breakpoint
ALTER TABLE "mockInterview" ADD CONSTRAINT "mockInterview_jobPostId_JobPost_id_fk" FOREIGN KEY ("jobPostId") REFERENCES "public"."JobPost"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "CallInterview" ADD CONSTRAINT "CallInterview_jobPostId_JobPost_id_fk" FOREIGN KEY ("jobPostId") REFERENCES "public"."JobPost"("id") ON DELETE no action ON UPDATE no action;