CREATE TABLE "JobDetails" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
	"jobTitle" varchar(255),
	"jobCategories" varchar(255)[],
	"jobTypes" varchar(255)[],
	"workplace" varchar(100),
	"country" varchar(100),
	"city" varchar(100),
	"careerLevel" varchar(100),
	"minExperience" integer,
	"maxExperience" integer,
	"minSalary" integer,
	"maxSalary" integer,
	"currency" varchar(20),
	"period" varchar(20),
	"hideSalary" boolean,
	"additionalSalary" varchar(255),
	"vacancies" integer,
	"jobDescription" text,
	"jobRequirements" text,
	"skills" varchar(255),
	"gender" varchar(50),
	"education" varchar(100),
	"academicExcellence" boolean,
	"createdAt" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "JobPost" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
	"jobTitle" varchar(255),
	"jobCategories" varchar(255)[],
	"jobTypes" varchar(255)[],
	"workplace" varchar(100),
	"country" varchar(100),
	"city" varchar(100),
	"careerLevel" varchar(100),
	"minExperience" integer,
	"maxExperience" integer,
	"minSalary" integer,
	"maxSalary" integer,
	"currency" varchar(20),
	"period" varchar(20),
	"hideSalary" boolean,
	"additionalSalary" varchar(255),
	"vacancies" integer,
	"jobDescription" text,
	"jobRequirements" text,
	"skills" varchar(255),
	"gender" varchar(50),
	"education" varchar(100),
	"academicExcellence" boolean,
	"createdAt" timestamp DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "CallInterview" ALTER COLUMN "jobDescription" SET DATA TYPE varchar(255);--> statement-breakpoint
ALTER TABLE "mockInterview" DROP COLUMN "jobTitle";--> statement-breakpoint
ALTER TABLE "mockInterview" DROP COLUMN "jobCategories";--> statement-breakpoint
ALTER TABLE "mockInterview" DROP COLUMN "jobTypes";--> statement-breakpoint
ALTER TABLE "mockInterview" DROP COLUMN "workplace";--> statement-breakpoint
ALTER TABLE "mockInterview" DROP COLUMN "country";--> statement-breakpoint
ALTER TABLE "mockInterview" DROP COLUMN "city";--> statement-breakpoint
ALTER TABLE "mockInterview" DROP COLUMN "careerLevel";--> statement-breakpoint
ALTER TABLE "mockInterview" DROP COLUMN "minExperience";--> statement-breakpoint
ALTER TABLE "mockInterview" DROP COLUMN "maxExperience";--> statement-breakpoint
ALTER TABLE "mockInterview" DROP COLUMN "minSalary";--> statement-breakpoint
ALTER TABLE "mockInterview" DROP COLUMN "maxSalary";--> statement-breakpoint
ALTER TABLE "mockInterview" DROP COLUMN "currency";--> statement-breakpoint
ALTER TABLE "mockInterview" DROP COLUMN "period";--> statement-breakpoint
ALTER TABLE "mockInterview" DROP COLUMN "hideSalary";--> statement-breakpoint
ALTER TABLE "mockInterview" DROP COLUMN "additionalSalary";--> statement-breakpoint
ALTER TABLE "mockInterview" DROP COLUMN "vacancies";--> statement-breakpoint
ALTER TABLE "mockInterview" DROP COLUMN "jobDescription";--> statement-breakpoint
ALTER TABLE "mockInterview" DROP COLUMN "jobRequirements";--> statement-breakpoint
ALTER TABLE "mockInterview" DROP COLUMN "skills";--> statement-breakpoint
ALTER TABLE "mockInterview" DROP COLUMN "gender";--> statement-breakpoint
ALTER TABLE "mockInterview" DROP COLUMN "education";--> statement-breakpoint
ALTER TABLE "mockInterview" DROP COLUMN "academicExcellence";--> statement-breakpoint
ALTER TABLE "CallInterview" DROP COLUMN "jobTitle";--> statement-breakpoint
ALTER TABLE "CallInterview" DROP COLUMN "jobCategories";--> statement-breakpoint
ALTER TABLE "CallInterview" DROP COLUMN "jobTypes";--> statement-breakpoint
ALTER TABLE "CallInterview" DROP COLUMN "workplace";--> statement-breakpoint
ALTER TABLE "CallInterview" DROP COLUMN "country";--> statement-breakpoint
ALTER TABLE "CallInterview" DROP COLUMN "city";--> statement-breakpoint
ALTER TABLE "CallInterview" DROP COLUMN "careerLevel";--> statement-breakpoint
ALTER TABLE "CallInterview" DROP COLUMN "minExperience";--> statement-breakpoint
ALTER TABLE "CallInterview" DROP COLUMN "maxExperience";--> statement-breakpoint
ALTER TABLE "CallInterview" DROP COLUMN "minSalary";--> statement-breakpoint
ALTER TABLE "CallInterview" DROP COLUMN "maxSalary";--> statement-breakpoint
ALTER TABLE "CallInterview" DROP COLUMN "currency";--> statement-breakpoint
ALTER TABLE "CallInterview" DROP COLUMN "period";--> statement-breakpoint
ALTER TABLE "CallInterview" DROP COLUMN "hideSalary";--> statement-breakpoint
ALTER TABLE "CallInterview" DROP COLUMN "additionalSalary";--> statement-breakpoint
ALTER TABLE "CallInterview" DROP COLUMN "vacancies";--> statement-breakpoint
ALTER TABLE "CallInterview" DROP COLUMN "jobRequirements";--> statement-breakpoint
ALTER TABLE "CallInterview" DROP COLUMN "skills";--> statement-breakpoint
ALTER TABLE "CallInterview" DROP COLUMN "gender";--> statement-breakpoint
ALTER TABLE "CallInterview" DROP COLUMN "education";--> statement-breakpoint
ALTER TABLE "CallInterview" DROP COLUMN "academicExcellence";