CREATE TABLE "CVAnalysis" (
	"id" integer PRIMARY KEY DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"userId" varchar(255) NOT NULL,
	"originalFileName" varchar(255),
	"extractedText" text,
	"parsedData" jsonb NOT NULL,
	"feedback" text,
	"analysisStatus" varchar(50) DEFAULT 'completed',
	"createdAt" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "JobRecommendation" (
	"id" integer PRIMARY KEY DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"userId" varchar(255) NOT NULL,
	"jobDetailsId" integer NOT NULL,
	"matchScore" integer,
	"recommendationReason" text,
	"isViewed" boolean DEFAULT false,
	"isApplied" boolean DEFAULT false,
	"createdAt" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "UserProfile" (
	"id" integer PRIMARY KEY DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"userId" varchar(255) NOT NULL,
	"email" varchar(255) NOT NULL,
	"name" varchar(255),
	"phone" varchar(50),
	"profilePhoto" varchar(500),
	"currentPosition" varchar(255),
	"currentCompany" varchar(255),
	"location" varchar(255),
	"summary" text,
	"skills" varchar(255)[],
	"languages" varchar(100)[],
	"certifications" varchar(255)[],
	"education" jsonb,
	"experience" jsonb,
	"cvAnalysisId" integer,
	"isProfileComplete" boolean DEFAULT false,
	"createdAt" timestamp DEFAULT now(),
	"updatedAt" timestamp DEFAULT now(),
	CONSTRAINT "UserProfile_userId_unique" UNIQUE("userId"),
	CONSTRAINT "UserProfile_email_unique" UNIQUE("email")
);
--> statement-breakpoint
ALTER TABLE "CallInterview" ADD COLUMN "jobDetailsId" integer;--> statement-breakpoint
ALTER TABLE "JobRecommendation" ADD CONSTRAINT "JobRecommendation_jobDetailsId_JobDetails_id_fk" FOREIGN KEY ("jobDetailsId") REFERENCES "public"."JobDetails"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "UserProfile" ADD CONSTRAINT "UserProfile_cvAnalysisId_CVAnalysis_id_fk" FOREIGN KEY ("cvAnalysisId") REFERENCES "public"."CVAnalysis"("id") ON DELETE no action ON UPDATE no action;