CREATE TABLE "sessionCheatingDetection" (
	"id" integer PRIMARY KEY DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"sessionId" varchar NOT NULL,
	"mockId" varchar NOT NULL,
	"userEmail" varchar,
	"sessionStartTime" timestamp NOT NULL,
	"sessionEndTime" timestamp,
	"sessionDuration" integer DEFAULT 0,
	"sessionCheatingDetection" jsonb,
	"sessionCheatingRiskScore" integer DEFAULT 0,
	"sessionCheatingAlertsCount" integer DEFAULT 0,
	"sessionCheatingSeverityLevel" varchar(20) DEFAULT 'low',
	"sessionCheatingViolations" jsonb,
	"sessionCheatingDevices" jsonb,
	"sessionCheatingMovementPatterns" jsonb,
	"sessionDetectionHistory" jsonb,
	"sessionAlerts" jsonb,
	"sessionEnhancedMetrics" jsonb,
	"sessionDetectionSettings" jsonb,
	"createdAt" timestamp DEFAULT now(),
	"updatedAt" timestamp DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "mockInterview" ADD COLUMN "isHidden" boolean DEFAULT false;