import { NextResponse } from 'next/server';
import { auth } from '@clerk/nextjs/server';
import { db } from '@/utils/db';
import { UserConnections, UserProfile } from '@/utils/schema';
import { eq, and, or } from 'drizzle-orm';

export async function POST(req) {
  try {
    console.log('=== Starting send-request API ===');
    
    // Get authenticated user
    const { userId } = await auth();
    if (!userId) {
      return NextResponse.json(
        { error: 'Authentication required' },
        { status: 401 }
      );
    }

    console.log('Authenticated user ID:', userId);
    
    const body = await req.json();
    console.log('Request body:', body);
    
    const { recipientEmail } = body;

    if (!recipientEmail) {
      return NextResponse.json(
        { error: 'Recipient email is required' },
        { status: 400 }
      );
    }

    console.log('Looking for user with email:', recipientEmail);

    // Find the recipient user by email
    const recipientUser = await db
      .select()
      .from(UserProfile)
      .where(eq(UserProfile.email, recipientEmail))
      .limit(1);

    console.log('Recipient user found:', recipientUser.length);

    if (!recipientUser.length) {
      return NextResponse.json(
        { error: 'User not found with this email address' },
        { status: 404 }
      );
    }

    const recipientId = recipientUser[0].userId;
    console.log('Recipient ID:', recipientId);

    // Check if requester is trying to add themselves
    if (userId === recipientId) {
      return NextResponse.json(
        { error: 'You cannot add yourself as a friend' },
        { status: 400 }
      );
    }

    // Check if connection already exists
    const existingConnection = await db
      .select()
      .from(UserConnections)
      .where(
        or(
          and(
            eq(UserConnections.requesterId, userId),
            eq(UserConnections.recipientId, recipientId)
          ),
          and(
            eq(UserConnections.requesterId, recipientId),
            eq(UserConnections.recipientId, userId)
          )
        )
      )
      .limit(1);

    console.log('Existing connection found:', existingConnection.length);

    if (existingConnection.length > 0) {
      const connection = existingConnection[0];
      
      if (connection.status === 'accepted') {
        return NextResponse.json(
          { error: 'You are already friends with this user' },
          { status: 400 }
        );
      } else if (connection.status === 'pending') {
        if (connection.requesterId === userId) {
          return NextResponse.json(
            { error: 'Friend request already sent' },
            { status: 400 }
          );
        } else {
          return NextResponse.json(
            { error: 'You have a pending friend request from this user' },
            { status: 400 }
          );
        }
      } else if (connection.status === 'blocked') {
        return NextResponse.json(
          { error: 'Cannot send request to blocked user' },
          { status: 400 }
        );
      }
    }

    console.log('Creating new connection with:', { userId, recipientId });

    // Create new friend request
    const newConnection = await db
      .insert(UserConnections)
      .values({
        requesterId: userId,
        recipientId,
        status: 'pending',
        // createdAt and updatedAt will be auto-generated by defaultNow()
      })
      .returning();

    console.log('New connection created:', newConnection);
    console.log('Connection ID:', newConnection[0]?.id);
    console.log('Full connection data:', JSON.stringify(newConnection[0], null, 2));

    return NextResponse.json({
      success: true,
      message: 'Friend request sent successfully',
      connection: newConnection[0],
    });

  } catch (error) {
    console.error('Error in send-request API:', error);
    console.error('Error stack:', error.stack);
    console.error('Error type:', typeof error);
    
    return NextResponse.json(
      { 
        error: 'Failed to send friend request', 
        details: error.message,
        type: typeof error,
        stack: error.stack
      },
      { status: 500 }
    );
  }
} 